-- Mevcut tabloları temizle
DROP TABLE IF EXISTS KATILIM;
DROP TABLE IF EXISTS ETKINLIK;
DROP TABLE IF EXISTS KULLANICI;


CREATE TABLE KULLANICI (
    ID              INT AUTO_INCREMENT PRIMARY KEY,
    KULLANICI_ADI   VARCHAR(255) NOT NULL UNIQUE,
    SIFRE           VARCHAR(255) NOT NULL,
    AD_SOYAD        VARCHAR(255),
    ROL             VARCHAR(25)  NOT NULL,
    EPOSTA          VARCHAR(255) NOT NULL,
    TELEFON         VARCHAR(11) NOT NULL
);


CREATE TABLE ETKINLIK (
    ID              INT AUTO_INCREMENT PRIMARY KEY,
    BASLIK          VARCHAR(255) NOT NULL,
    ACIKLAMA        VARCHAR(2000),
    TARIH           TIMESTAMP NOT NULL,
    YER             VARCHAR(255),
    KONTENJAN       INT NOT NULL,
    OLUSTURAN_ID    INT,
    DURUM 			VARCHAR(50) NOT NULL,
    CONSTRAINT FK_ETKINLIK_KULLANICI
        FOREIGN KEY (OLUSTURAN_ID)
        REFERENCES KULLANICI(ID)
);


CREATE TABLE KATILIM (
    ID              INT AUTO_INCREMENT PRIMARY KEY,
    ETKINLIK_ID     INT NOT NULL,
    KULLANICI_ID    INT NOT NULL,
    KAYIT_ZAMANI    TIMESTAMP NOT NULL,
    CONSTRAINT FK_KATILIM_ETKINLIK
        FOREIGN KEY (ETKINLIK_ID)
        REFERENCES ETKINLIK(ID),
    CONSTRAINT FK_KATILIM_KULLANICI
        FOREIGN KEY (KULLANICI_ID)
        REFERENCES KULLANICI(ID)
);
